version: '3'

services:
  smart-contract:
    container_name: smart-contract
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/go/src/smart-contract
    ports:
      - "9000:9000"
